name: Group01-Glaciers
channels:
 - conda-forge
dependencies:
 - python=3.11.4*
 - pip
 - cartopy >= 0.20.0
 - datashader
 - h5netcdf
 - h5py
 - holoviews
 - hvplot
 - jupyterlab
 - matplotlib-base
 - nc-time-axis
 - netcdf4
 - numpy
 - pandas
 - scipy
 - xarray
 - xarrayutils
 - xarray_leaflet
 - xarray-spatial
